import type { Beat, Profile } from "./supabase/types";

export const MOCK_PROFILE: Profile = {
  id: "mock-1",
  username: "ljung",
  display_name: "LJUNG",
  bio: "Produsent fra Oslo. Spesialiserer meg på dark drill og melodisk trap.",
  avatar_url: null,
  stripe_account_id: null,
  stripe_onboarding_complete: false,
  instagram_url: null,
  spotify_url: null,
  soundcloud_url: null,
  created_at: new Date().toISOString(),
};

export const MOCK_BEATS: Beat[] = [
  {
    id: "1",
    producer_id: "mock-1",
    title: "NATT I OSLO",
    description: "",
    genre: "Drill",
    bpm: 140,
    key: "A min",
    tags: ["dark", "melodic", "strings"],
    price: 1200,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
  {
    id: "2",
    producer_id: "mock-1",
    title: "SOLOPPGANG",
    description: "",
    genre: "Afro",
    bpm: 98,
    key: "C maj",
    tags: ["afro", "summer", "vibes"],
    price: 800,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
  {
    id: "3",
    producer_id: "mock-1",
    title: "BLODBAD",
    description: "",
    genre: "Drill",
    bpm: 145,
    key: "F# min",
    tags: ["hard", "drill", "dark"],
    price: 1500,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
  {
    id: "4",
    producer_id: "mock-1",
    title: "MIDNATT",
    description: "",
    genre: "Trap",
    bpm: 155,
    key: "D min",
    tags: ["trap", "808", "melodic"],
    price: 1100,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
  {
    id: "5",
    producer_id: "mock-1",
    title: "VINTER",
    description: "",
    genre: "R&B",
    bpm: 85,
    key: "Eb maj",
    tags: ["smooth", "rb", "chill"],
    price: 700,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
  {
    id: "6",
    producer_id: "mock-1",
    title: "GATEKJØKKEN",
    description: "",
    genre: "Drill",
    bpm: 138,
    key: "G min",
    tags: ["street", "drill", "hard"],
    price: 1300,
    exclusive_price: null,
    exclusively_sold: false,
    cover_url: null,
    audio_preview_url: null,
    project_file_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    producer: MOCK_PROFILE,
  },
];
